name: Build and Deploy

on:

  push:

    branches: [main]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    environment: github-pages

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js

        uses: actions/setup-node@v2

        with:

          node-version: "18"

      - name: Clear npm cache

        run: npm cache clean --force

      - name: Install dependencies

        run: npm ci

      - name: Install dev dependencies

        run: npm install --only=dev

      - name: Print working directory

        run: |

          pwd

          ls -la

      - name: Debug Environment Variables
        run: |
          echo "SUPABASE_URL is set: ${{ secrets.SUPABASE_URL != '' }}"
          echo "SUPABASE_KEY is set: ${{ secrets.SUPABASE_KEY != '' }}"
          echo "TEACHER_PASSWORD is set: ${{ secrets.TEACHER_PASSWORD != '' }}"
            

      - name: Build

        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          TEACHER_PASSWORD: ${{ secrets.TEACHER_PASSWORD }}
        run: 
          npm run build
          
      - name: Check for index.html

        run: |

          if [ ! -f dist/index.html ]; then

            echo "index.html not found in dist folder"

            echo "Contents of current directory:"

            ls -la

            echo "Contents of dist folder (if it exists):"

            ls -la dist || echo "dist folder does not exist"

            exit 1

          fi

      - name: Create .nojekyll file
        run: touch dist/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
